version: 2.1

jobs:
  build:
    docker:
      - image: node:11.10.1

    working_directory: ~/repo
    steps:
      - checkout

        #      - restore_cache:
        #  keys:
        #      - v1-dependencies-{{checksum "companion-app/package.json"}}
        #      - v1-dependencies-


        #- run: yarn --cwd companion-app/ install

        #- save_cache:
        #  paths:
        #      - companion-app/node_modules
        #  key: v1-dependencies-{{checksum "companion-app/package.json"}}

      # run tests!
      #- run: yarn --cwd companion-app/ test

        #- run: yarn --cwd companion-app/ build

      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
         name: Install CMAKE
         command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          name: Creating Binary Files
          command: 'cd AudioEngine/ && make CPU=X86 CONFIG=Debug'
      - run:
          name: Point Unit Testing
          command: 'cd AudioEngine/ && ./audio_test'
